spring:
    application:
        name: resume-roaster-ai
    output:
        ansi:
            enabled: ALWAYS

resumeroaster:
    corenlp:
        annotators: tokenize,ssplit,pos,lemma,ner
        use-su-time: false
        replacement-template: "[%s]"
        target-tags:
            - PERSON
            - EMAIL
            - URL
            - PHONE_NUMBER
            - CITY
            - STATE_OR_PROVINCE
            - COUNTRY

mlflow:
    tracking-uri: ${MLFLOW_TRACKING_URI}
    username: ${MLFLOW_TRACKING_USERNAME}
    password: ${MLFLOW_TRACKING_PASSWORD}
    model-name: ${MLFLOW_MODEL_NAME:distilbert-ner}
    model-version: ${MLFLOW_MODEL_VERSION:1}

langchain4j:
    # Replicates the OpenAI Chat Completions / Responses API for both Chat Model and Streaming Chat Model
    open-ai:
        chat-model: &openai-config
            base-url: ${LLM_BASE_URL}
            api-key: ${LLM_API_KEY}
            model-name: ${LLM_MODEL_NAME}
        streaming-chat-model: *openai-config
